version: "3.8"

services:
  api:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    container_name: exempli-backend
    env_file: ./.env
    ports:
        - "8000:8000"
    networks: 
      - app
    command: sh -c "npx knex migrate:latest && npm run express"
    depends_on: 
      - db

  db:
    image: postgres:13
    env_file: ./.env
    volumes:
        - db:/var/lib/postgresql/data
    networks: 
      - app
      
networks:
  app:

volumes:
  db:
